models/Item.php
<?php

namespace app\models;

use Yii;
/**
 * This is the model class for table "Item".
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property integer $price
 */
class Item extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'item';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['description'], 'string'],
            [['price'], 'integer'],
            [['name'], 'string', 'max' => 255],
            [['name', 'price'], 'required']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Наименование',
            'description' => 'Описание',
            'price' => 'Цена',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrderItem()
    {
        return $this->hasMany(OrderItems::className(), ['id_item' => 'id']);
    }
    
    public static function findFromString($string) {
        return \Yii::$app->db->createCommand(
            "SELECT * FROM item WHERE name LIKE :string OR description LIKE :string OR price LIKE :string",
            [':string' => "%$string%"]
        )->queryAll();
    }
}

controllers/ItemController.php
<?php


namespace app\controllers;

use Yii;
use yii\data\ActiveDataProvider;
use yii\data\ArrayDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use app\models\Item;

class ItemController extends Controller
{
    /**
     * actionIndex
     *
     * @return void
     */
    public function actionIndex()
    {

        $request = \Yii::$app->request;

        if ($request->get('search')) {
            $searchData = Item::findFromString($request->get('search-string'));
        }
        else {
            $searchData = Item::find()->orderBy(['name' => SORT_ASC])->asArray()->all();
        }
        $dataProvider = new ArrayDataProvider([
            'allModels' => $searchData,
            'pagination' => [
                'pageSize' => 30,
            ],
            'sort' => [
                'attributes' => ['id'],
            ],
        ]);
        $dataProvider->pagination->pageSize = 30;

        return $this->render('index', compact('dataProvider'));
    }

    /**
     * actionAdd
     * to add items
     *
     * @return string
     */
    public function actionAdd()
    {
        $model = new Item();

        if ($model->load(\Yii::$app->request->post()))
        {
            if ($model->save()) {
                \Yii::$app->session->setFlash('success', "Товар добавлен");
                return $this->redirect(["index"]);
            }
        }

        return $this->render('form', compact('model'));
    }

    /**
     * actionEdit
     * to edit items
     * @param  int $id
     *
     * @return string
     */
    public function actionEdit($id)
    {
        $model = $this->findModel($id);

        if ($model->load(\Yii::$app->request->post()))
        {
            if ($model->save()) {
                \Yii::$app->session->setFlash('success', "Товар добавлен");
                return $this->redirect(["index"]);
            }
                
        }

        return $this->render('form', compact('model'));
    }

    /**
     * actionDelete
     * to delete items
     * @param  mixed $id
     *
     * @return void
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        \Yii::$app->session->setFlash('success', "Товар удалён");

        return $this->redirect(['index']);
    }

    /**
     * findModel
     * 
     * @param  mixed $id
     *
     * @return \yii\db\ActiveQuery|yii\web\NotFoundHttpException
     */
    protected function findModel($id)
    {
        if (($model = Item::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/item/form.php
<?php

use yii\widgets\ActiveForm;
use yii\helpers\Html;

$this->title = 'Редактирование товара';


?>

<div class="page-header">
    <h3 class="page-title"> Товары </h3>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/item/">Товары</a></li>
            <li class="breadcrumb-item active" aria-current="page">Редактирование</li>
        </ol>
    </nav>
</div>

<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Редактирование товара</h4>
            <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

            <div class="form-group">
                <div class="col-12">
                        <?= $form->field($model, 'name')->textInput() ?>
                        <?= $form->field($model, 'price')->textInput() ?>
                </div>
            </div>
            <div class="form-group">
                <div class="col-12">
                    <?= $form->field($model, 'description')->textarea() ?>
                </div>
            </div>

            <div class="clearfix"></div>

            <div class="form-group">
                <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
                <a href="/crm/products/" class="btn btn-default" role="button">К списку продуктов</a>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/item/index.php
<?php

use yii\grid\GridView;
use yii\helpers\Html;

$this->title = 'Просмотр товаров';


?>

<div class="page-header">
    <h2 class="display1"> Товары </h3>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/item/">Товары</a></li>
            <li class="breadcrumb-item active" aria-current="page">Просмотр</li>
        </ol>
    </nav>
</div>

<?php if (Yii::$app->session->hasFlash('success')) : ?>

    <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <?php echo Yii::$app->session->getFlash('success'); ?>
    </div>
<?php endif; ?>

<div class="col-12 row">
    <div class="col-3">
        <p>
            <?= Html::a('Создать новый товар', ['add'], ['class' => 'btn btn-dark btn-fw']) ?>
        </p>
    </div>
    <div class="col-6">

    </div>
    <div class="col-3">
        <div class="form-group">
            <form class="search-form d-none d-md-block" action="/item/" method="get">
                <div class="input-group">
                    <input type="hidden" name="search" value="1">
                    <input type="text" class="form-control" placeholder="Название, описание и т.п." title="Поиск" name="search-string">
                    <div class="input-group-append">
                        <button class="btn btn-sm btn-primary" type="submit">Поиск</button>
                    </div>
                </div>
            </form>
        </div>

    </div>

</div>

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <?php if(isset($_GET['search'])) : ?>
            <h2 class="display2"> Поиск по запросу: <?= $_GET['search-string'] ?> </h3>
            <?php endif ?>

            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'columns' => [

                    [
                        'attribute' => 'name',
                        'format' => 'html',
                        'header' => 'Продукт',
                        'value' => function ($data) {
                            return $data['name'];
                        }
                    ],

                    [
                        'attribute' => 'description',
                        'format' => 'html',
                        'header' => 'Описание',
                        'value' => function ($data) {
                            return $data['description'];
                        }
                    ],

                    [
                        'attribute' => 'price',
                        'header' => 'Цена',
                        'value' => function ($data) {
                            return $data['price'] . ' ₽';
                        }
                    ],

                    [
                        'class' => 'yii\grid\ActionColumn',
                        'buttons' => [
                            'edit' => function ($url, $model) {
                                if (isset($_GET['page'])) {
                                    $page = $_GET['page'];
                                } else {
                                    $page = 1;
                                }
                                $customUrl = Yii::$app->getUrlManager()->createUrl(['/item/edit', 'id' => $model['id']]);
                                return Html::a('<span><i class="fas fa-pencil-alt" aria-hidden="true"></i> Редактировать</span>', $customUrl, [
                                    'class' => 'btn btn-inverse-primary btn-fw',
                                    'role' => 'button',
                                    'title' => 'Редактировать'
                                ]);
                            },
                            'delete' => function ($url, $model) {
                                $customUrl = Yii::$app->getUrlManager()->createUrl(['/item/delete', 'id' => $model['id']]);
                                return Html::a('<span><i class="fa fa-ban" aria-hidden="true"></i> Удалить</span>', $customUrl, [
                                    'class' => 'btn btn-inverse-danger btn-fw',
                                    'role' => 'button',
                                    'title' => 'Удалить'
                                ]);
                            }
                        ],
                        'template' => '{edit} {delete}',
                    ],
                ],
                'tableOptions' => ['class' => 'table table-hover']
            ]); ?>
        </div>
    </div>
</div>