models/Orders.php
<?php

namespace app\models;

use app\controllers\AppController;
use Yii;
use yii\helpers\Json;

/**
 * This is the model class for table "orders".
 *
 * @property integer $id
 * @property integer $id_status
 * @property integer $date
 * @property string $number
 *
 * @property OrderItems[] $orderItems
 * @property OrderStatuses $idStatus
 */
class Orders extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'orders';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_status', 'date'], 'integer'],
            [['number'], 'string', 'max' => 255],
            [['id_status'], 'exist', 'skipOnError' => true, 'targetClass' => OrderStatuses::className(), 'targetAttribute' => ['id_status' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_status' => 'Статус',
            'number' => 'Номер',
            'date' => 'Дата',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getItems()
    {
        return $this->hasMany(OrderItems::className(), ['id_order' => 'id']);
    }

    public function getItem()
    {
        return $this->hasMany(Item::className(), ['id' => 'id_item'])
            ->via('items');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStatus()
    {
        return $this->hasOne(OrderStatuses::className(), ['id' => 'id_status']);
    }
}

controllers/OrdersController.php
<?php


namespace app\controllers;

use app\models\Item;
use app\models\OrderItems;
use yii\data\ActiveDataProvider;
use yii\data\ArrayDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use app\models\Orders;
use app\models\OrderStatuses;
use yii\helpers\Json;

class OrdersController extends Controller
{
    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;

        return parent::beforeAction($action);
    }
    /**
     * actionIndex
     * Orders Page
     * @return string
     */
    public function actionIndex()
    {

        $request = \Yii::$app->request;
        $statuses = OrderStatuses::find()->asArray()->all();

        if ($request->get('search')) {
            $searchData = Orders::find()->select('*')->with('items.item', 'status')->orderBy(['date' => SORT_DESC]);

            if ($request->get('status') > 0) {
                $searchData->where(['id_status' => $request->get('status')]);
            } else {
                $searchData->where(['not', ['id_status' => 0]]);
            }

            if ($request->get('search-string')) {
                $searchData->andWhere(['number' => $request->get('search-string')]);
            }

            if ($request->get('date')) {
                $DATE = explode('-', $request->get('date'));
                if (count($DATE) === 1) {
                    $STARTDATE = "-1 month";
                    $ENDDATE = $request->get('date');
                }
                if (count($DATE) === 2) {
                    $STARTDATE = $DATE[0];
                    $ENDDATE = $DATE[1];
                }
                $STARTDATE = strtotime($STARTDATE);
                $ENDDATE = strtotime($ENDDATE);

                $searchData->andWhere(['>=', 'date', $STARTDATE])->andWhere(['<=', 'date', $ENDDATE]);
            }


            $searchData->asArray();
            $dataProvider = new ActiveDataProvider([
                'query' => $searchData,
                'pagination' => [
                    'pageSize' => 30,
                ],
                'sort' => [
                    'attributes' => ['id'],
                ],
            ]);
        } else {

            $searchData = Orders::find()->with('items.item', 'status')->orderBy(['date' => SORT_DESC])->asArray()->all();
            $dataProvider = new ArrayDataProvider([
                'allModels' => $searchData,
                'pagination' => [
                    'pageSize' => 30,
                ],
                'sort' => [
                    'attributes' => ['id'],
                ],
            ]);
        }


        $dataProvider->pagination->pageSize = 30;

        return $this->render('index', compact('dataProvider', 'statuses'));
    }

    /**
     * actionAdd
     * to add Orders
     * @return string 
     */
    public function actionAdd()
    {

        $model = new Orders();

        $orderItems = new OrderItems();
        $items = Item::find()->all();
        $orderStatus = OrderStatuses::find()->all();
        if (\Yii::$app->request->isAjax) {
            $post = \Yii::$app->request->post();
            $itemsAjax = array_filter($post['items']);

            $model->id_status = $post['orderStatus'];
            $model->number = $post['orderNumber'];
            $model->date = strtotime('now');

            if ($model->save()) {
                foreach ($itemsAjax as $item => $count) {
                    $newOrderItem = new OrderItems();
                    $newOrderItem->id_order = $model->id;
                    $newOrderItem->id_item = $item;
                    $newOrderItem->count = (int)$count;
                    $newOrderItem->save();
                }

                \Yii::$app->session->setFlash('success', "Товар добавлен");
                return Json::encode([
                    'error' => 0,
                ]);
            }
        }


        return $this->render('form', compact('model', 'items', 'orderItems', 'orderStatus'));
    }

    /**
     * actionEdit
     * to edit orders
     * @param  int $id
     *
     * @return string
     */
    public function actionEdit($id)
    {
        $model = $this->findModel($id);

        $orderItems = OrderItems::find()->where(['id_order' => $id])->with('item')->all();
        $items = Item::find()->all();
        $orderStatus = OrderStatuses::find()->all();

       if (\Yii::$app->request->isAjax) {
            $post = \Yii::$app->request->post();
            $itemsAjax = array_filter($post['items']);

            $model->id_status = $post['orderStatus'];
            $model->number = $post['orderNumber'];
            $model->date = strtotime('now');

            if ($model->save()) {
                foreach ($itemsAjax as $item => $count) {
                    $newOrderItem = new OrderItems();
                    $newOrderItem->id_order = $model->id;
                    $newOrderItem->id_item = $item;
                    $newOrderItem->count = (int)$count;
                    $newOrderItem->save();
                }

                \Yii::$app->session->setFlash('success', "Товар добавлен");
                return Json::encode([
                    'error' => 0,
                ]);
            }
        }

        return $this->render('form', compact('model', 'items', 'orderItems', 'orderStatus'));
    }

    /**
     * actionDelete
     * to delete orders
     * @param  int $id
     *
     * @return void
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        \Yii::$app->session->setFlash('success', "Товар удалён");

        return $this->redirect(['index']);
    }

    /**
     * findModel
     * 
     * @param int $id
     *
     * @return \yii\db\ActiveQuery|yii\web\NotFoundHttpException
     */
    protected function findModel($id)
    {
        if (($model = Orders::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/orders/form.php
<?php

use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;

$this->title = 'Редактирование заказа';

$Items = ArrayHelper::map($items, 'id', 'name');

$Statuses = ArrayHelper::map($orderStatus, 'id', 'name');
$StautusParams = [
    'class' => 'selectpicker',
    'data-width' => '100%',
    'title' => 'Выберите статус',
    'options' => [$model->id_status => ['Selected' => true]],
];


?>

<div class="page-header">
    <h3 class="page-title"> Заказы </h3>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/item/">Заказы</a></li>
            <li class="breadcrumb-item active" aria-current="page">Редактирование</li>
        </ol>
    </nav>
</div>

<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Редактирование заказа</h4>
            <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

            <div class="form-group">
                <div class="col-12">
                    <?= $form->field($model, 'number')->textInput() ?>
                    <?= $form->field($model, 'id_status')->dropDownList($Statuses, $StautusParams) ?>
                </div>
                <div class="col-12 row">
                    <div class="col-6">
                        <h5 class="card-title">Товар</h4>
                    </div>
                    <div class="col-6">
                        <h5 class="card-title">Количество</h4>
                    </div>
                </div>
                <div class="items">
                    <?php foreach ($orderItems as $ordIt) : ?>
                        <div class="exist-item row" id="order-item-block">
                            <div class="col-6" id="order-item">
                                <select id="orderitems-id_item" class="form-control form-control-sm" name="OrderItems[id_item]" title="Выберите товар" data-live-search="true" mobile="true" data-width="100%">
                                    <option value=""> </option>
                                    <?php foreach ($Items as $item => $name) : ?>
                                        <option value="<?= $item ?>" <?= ($ordIt['id_item'] == $item) ? ' selected' : '' ?>><?= $name ?></option>
                                    <?php endforeach ?>
                                </select>
                            </div>

                            <div class="col-6" id="order-item-count">
                                <input id="item-count" class="form-control form-control-sm count" type="text" value="<?= $ordIt['count'] ?>">
                            </div>
                        </div>
                    <?php endforeach ?>
                </div>
            </div>

            <div class="new-item row col-12">
                <div class="col-3">
                    <button type="button" class="btn btn-info btn-appent-item">Добавить</button>
                </div>
            </div>

            </br>

            <div class="form-group">
                <button type="button" class="btn btn-success btn-save-order">Сохранить</button>
                <a href="/orders/" class="btn btn-default" role="button">К списку заказов</a>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

<script>
    $('body')
        .on('click', '.btn-appent-item', function() {
            $('.items').append('<div class="exist-item row"><div class="col-6"><select id="orderitems-id_item" class="form-control form-control-sm" name="OrderItems[id_item]" title="Выберите товар" data-live-search="true" mobile="true" data-width="100%"><option value=""> </option><option value=""></option></select></div><div class="col-6"><input class="form-control form-control-sm count" type="text"></div></div>');
        })
        .on('click', '.btn-save-order', function() {
            var orderNumber = $('#orders-number').val();
            var orderStatus = $('#orders-id_status option:selected').val();

            var orderItems = $('.items');

            var itemsAndCounts = [];

            $('.items').each(function(index, value) {
                console.log(value);
            });
            $('*[id=order-item-block]:visible').each(function() {
                $(this).find('#orderitems-id_item option:selected').val()
                
                if (typeof itemsAndCounts[$(this).find('#orderitems-id_item option:selected').val()] !== "undefined") {
                    itemsAndCounts[$(this).find('#orderitems-id_item option:selected').val()] += Number($(this).find('#item-count').val());
                }
                else {
                    itemsAndCounts[$(this).find('#orderitems-id_item option:selected').val()] = Number($(this).find('#item-count').val())
                }
            });

            console.log(itemsAndCounts);

            $.ajax({
                        url: 'add',
                        data: {
                            orderNumber: orderNumber,
                            orderStatus: orderStatus,
                            items: itemsAndCounts
                            
                        },
                        dataType: 'json',
                        type: 'POST',
                        success: function (response) {
                            if (response.error === 0) {
                                console.log(response.data);
                                return document.location.href = 'http://34.94.53.225/orders/'
                            } else {
                                console.log(response.data);
                            }
                        },
                        error: function (xhr) {
                            console.log(xhr.responseText);
                        }
                    })
        })
</script>

views/orders/index.php
<?php

use yii\grid\GridView;
use yii\helpers\Html;

$this->title = 'Просмотр заказов';

$this->registerCssFile('/css/datepicker.min.css');
?>

<div class="page-header">
    <h2 class="display1"> Заказы </h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/item/">Заказы</a></li>
                <li class="breadcrumb-item active" aria-current="page">Просмотр</li>
            </ol>
        </nav>
</div>

<?php if (Yii::$app->session->hasFlash('success')) : ?>

    <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <?php echo Yii::$app->session->getFlash('success'); ?>
    </div>
<?php endif; ?>

<div class="col-12 row">
    <div class="col-3">
        <p>
            <?= Html::a('Создать новый заказ', ['add'], ['class' => 'btn btn-dark btn-fw']) ?>
        </p>
    </div>
    <div class="col-3">

    </div>
    <div class="col-6">
        <div class="form-group">
            <form class="search-form d-none d-md-block" action="/orders/" method="get">
                <div class="input-group">
                    <input id="date-picker" type="text" data-range="true" data-multiple-dates-separator=" - " class="form-control datepicker-here" name="date" />
                    <select class="form-control" name="status">
                        <option value="0">Любой</option>
                        <?php foreach ($statuses as $status) : ?>
                            <option value="<?= $status['id'] ?>"><?= $status['name'] ?></option>
                        <?php endforeach ?>
                    </select>
                    <input type="hidden" name="search" value="1">
                    <input type="text" class="form-control" placeholder="Название, описание и т.п." title="Поиск" name="search-string">
                    <div class="input-group-append">
                        <button class="btn btn-sm btn-primary" type="submit">Поиск</button>
                    </div>
                </div>
            </form>
        </div>

    </div>

</div>

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <?php if (isset($_GET['search'])) : ?>
                <h2 class="display2"> Поиск по запросу: <?= $_GET['search-string'] ?> </h3>
                <?php endif ?>

                <?= GridView::widget([
                    'dataProvider' => $dataProvider,
                    'columns' => [

                        [
                            'attribute' => 'number',
                            'format' => 'html',
                            'header' => 'Номер заказа',
                            'value' => function ($data) {
                                // print_r($data);
                                // die;
                                return $data['number'];
                            }
                        ],

                        [
                            'attribute' => 'status',
                            'format' => 'html',
                            'header' => 'Статус заказа',
                            'value' => function ($data) {
                                
                                return $data['status']['name'];
                            }
                        ],

                        [
                            'attribute' => 'price',
                            'header' => 'Цена',
                            'value' => function ($data) {
                                $summ = 0;
                                foreach ($data['items'] as $item) {
                                    $summ += $item['item']['price']*$item['count'];
                                }
                                return $summ . ' ₽';
                            }
                        ],

                        [
                            'attribute' => 'date',
                            'header' => 'Дата создания',
                            'value' => function ($data) {
                                return date('d.m.Y H:i', $data['date']);
                            }
                        ],

                        [
                            'class' => 'yii\grid\ActionColumn',
                            'buttons' => [
                                'edit' => function ($url, $model) {
                                    if (isset($_GET['page'])) {
                                        $page = $_GET['page'];
                                    } else {
                                        $page = 1;
                                    }
                                    $customUrl = Yii::$app->getUrlManager()->createUrl(['/orders/edit', 'id' => $model['id']]);
                                    return Html::a('<span><i class="fas fa-pencil-alt" aria-hidden="true"></i> Редактировать</span>', $customUrl, [
                                        'class' => 'btn btn-inverse-primary btn-fw',
                                        'role' => 'button',
                                        'title' => 'Редактировать'
                                    ]);
                                },
                                'delete' => function ($url, $model) {
                                    $customUrl = Yii::$app->getUrlManager()->createUrl(['/orders/delete', 'id' => $model['id']]);
                                    return Html::a('<span><i class="fa fa-ban" aria-hidden="true"></i> Удалить</span>', $customUrl, [
                                        'class' => 'btn btn-inverse-danger btn-fw',
                                        'role' => 'button',
                                        'title' => 'Удалить'
                                    ]);
                                }
                            ],
                            'template' => '{edit} {delete}',
                        ],
                    ],
                    'tableOptions' => ['class' => 'table table-hover']
                ]); ?>
        </div>
    </div>
</div>